AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API using SAM
Globals:
  Function:
    Runtime: nodejs14.x
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
    MemorySize: 128
    Timeout: 500
Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      SamResourceId: Table
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: packages/server/dist/get.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: get
      CodeUri: s3://om-sam1/efb5b7ceaf175b6585d865df2cda5de4
    Metadata:
      SamResourceId: GetUser
  PostUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: packages/server/dist/post.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: post
      CodeUri: s3://om-sam1/efb5b7ceaf175b6585d865df2cda5de4
    Metadata:
      SamResourceId: PostUser
  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: packages/server/dist/delete.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: delete
      CodeUri: s3://om-sam1/efb5b7ceaf175b6585d865df2cda5de4
    Metadata:
      SamResourceId: DeleteUser
